### ISSUE TITLE
Suppress or solve unreachable code warnings

### ISSUE THREAD

**Issue by Jjagg** [StbSharp/StbImageWriteSharp#1]
Because MG includes the source files directly we get these warnings when building MG.
Not sure if this is an issue with the code generation in Sichem or issue in the stb source code, but the compiler warns about this code:

https://github.com/StbSharp/StbImageWriteSharp/blob/4261b83db18cd8a8a6c776dae339b61603e63ff5/src/StbImageWriteSharp/StbImageWrite.Generated.cs#L623-L646

because only the third branch `256 <= 279` is ever reached. Would be nice if either this code was not generated or Sichem suppresses the warning by generating `#pragma warning disable 0162` at the start of files and restores it with `#pragma warning restore 0162` at the end of generated files.

**Comment by rds1983** [comment]
Fixed by removing unreachable code.
If you plan to update the submodule, be aware that latest StbSharp folder structure was somewhat simplified.
I think currently MG includes all source files from "StbImageWriteSharp/src/StbImageWriteSharp/".
Now, it's just "StbImageWriteSharp/src/".
