### ISSUE TITLE
Ошибка в WritePng

### ISSUE THREAD

**Issue by GlebSBrykin** [StbSharp/StbImageWriteSharp#2]
В методе WritePng(byte[], int, int, ColorComponents, Stream) есть рекурсия, приводящая к переполнению стека и невозможности сохранить png.
```
fixed (byte* b = &data[0])
{
	WritePng(data, width, height, components, dest);
}
```
В итоге указанный метод вызывает сам себя, а должен вызывать первый вариант этого метода, непосредственно выполняющий сохранение изображения.
```
fixed (byte* b = &data[0])
{
	WritePng((void*)b, width, height, components, dest);
}
```
Вот это исправленный кусок кода.

**Comment by rds1983** [comment]
Fixed. Спасибо за report.
